version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-world-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tthu698bemqj"
s3_prefix = "hello-world-lambda"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
